### ISSUE TITLE
Stroke

### ISSUE THREAD

**Issue by AlexDenisov** [AlexDenisov/FontasticIcons#16]
Drawing stroke if needed:

```
icon.borderWidth = 3.f;
icon.borderColor = [UIColor redColor];
```

![123](https://f.cloud.github.com/assets/1175576/108584/bbee288e-6a55-11e2-86ed-c9ec1ba7dd22.png)

**Comment by texastoland** [comment]
I thought about implementing that last time. I exposed a way to do it but not by setting a property. One reason is the icon gets scaled so stroke size is relative to font size instead of absolute which seemed unintuitive.

**Comment by AlexDenisov** [comment]
<blockquote>One reason is the icon gets scaled so stroke size is relative to font size</blockquote>

Hm... Are you sure? 
I thought that stroke could be set through `kCTStrokeWidthAttributeName` and `kCTStrokeColorAttributeName` attributes...

**Comment by texastoland** [comment]
Exactly. Currently any attribute can be [set](../blob/master/FontasticIcons/Sources/Classes/FIIconLayer.h#L15) like `[icon setIconAttribute:kCTStrokeWidthAttributeName value:(__bridge) @3];`. But since our text matrix gets [scaled](https://github.com/AlexDenisov/FontasticIcons/blob/master/FontasticIcons/Sources/Classes/FIIconLayer.m) (also in your original implementation) stroke width varies with icon bounds:

> This attribute, interpreted as a percentage of font point size, controls the text drawing mode: positive values effect drawing with stroke only; negative values are for stroke and fill.

I agree these should be added to `FIIconRendering` protocol though. Maybe as a percentage like `icon.strokeWidthRatio = 0.25;` (3 ÷ 12 = 0.25)? I could commit it tonight.

**Comment by texastoland** [comment]
Merged in `development`.
